# Book settings
title: DaveOnData's Introduction to SQL for Excel Users (Abridged)
author: David Langer
description: Selected SQL code selected from original blog to use with AdventureWorksDW database